version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    allow:
      - dependency-name: "jsbarcode"
      - dependency-name: "react"
      - dependency-name: "react-native"
      - dependency-name: "react-native-svg"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "react-native-svg"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"